In [1]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as seabornInstance 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.datasets import load_boston

# change the data type of gender,education_level,marital_status as new data train123mo.csv
# classify gender 1 as men and 0 as female
# classift education_level 0 as high school,1 as university and univiersity,2 as graduate school,3 as others,4 as unknow



path = 'C:\\Users\\user\\titan\\train123mo.csv'
data = pd.read_csv(path, header=None,names=['id','credit_limit','gender','education_level','marital_status','age','payment_delay_month3',
                                            'payment_delay_month2','payment_delay_month1','bill_amount_month3','bill_amount_month2',
                                            'bill_amount_month1','previous_payment_month3','previous_payment_month2','previous_payment_month1','previous_payment_month4'])

data

,id,credit_limit,gender,education_level,marital_status,age,payment_delay_month3,payment_delay_month2,payment_delay_month1,bill_amount_month3,bill_amount_month2,bill_amount_month1,previous_payment_month3,previous_payment_month2,previous_payment_month1,previous_payment_month4
0,0,75659.32872,1.0,2.0,1.0,53.0,0.0,0.0,0.0,97.336043,617.642189,515.513381,617.642189,515.513381,0.000000,97.336043
1,1,10119.28851,0.0,0.0,1.0,46.0,0.0,NaN,1.0,217.039935,107.684919,220.712322,0.000000,100.594674,22.241495,209.732445
2,2,13374.80610,0.0,1.0,1.0,31.0,1.0,1.0,1.0,13506.342420,5892.633733,6291.752821,752.120619,397.170110,397.501113,397.170110
3,3,157744.09660,1.0,2.0,1.0,34.0,0.0,0.0,1.0,14278.876050,18234.124720,13042.939540,18400.055470,1547.887184,2.558114,14368.707270
4,5,120385.03030,0.0,2.0,0.0,29.0,1.0,1.0,1.0,7130.249304,1572.472869,NaN,397.170110,0.000000,1395.861422,193.835523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20643,23203,48443.44654,1.0,2.0,0.0,29.0,-1.0,-1.0,-1.0,64.409146,64.409146,414.621668,64.409146,414.621668,134.155089,64.409146
20644,23204,110098.06710,0.0,1.0,1.0,36.0,1.0,1.0,1.0,19717.923360,15197.977010,12257.308490,754.001390,240.003713,239.255805,783.841260
20645,23205,237841.42300,0.0,1.0,1.0,42.0,1.0,1.0,1.0,202892.399200,147770.694800,22765.992910,2915.937494,397.170110,397.170110,3632.499761
20646,23206,105024.75430,0.0,1.0,1.0,34.0,-1.0,-1.0,-1.0,0.000000,0.000000,10.739167,0.000000,10.739167,77.300315,0.000000
20647,23207,141487.28530,0.0,1.0,1.0,28.0,1.0,1.0,1.0,90076.120680,91633.455600,98210.226450,1461.488930,3527.432995,2015.189286,1788.854382

In [2]:
#檢查是否有缺失項目
data.isnull().any()

id                         False
credit_limit               False
gender                      True
education_level             True
marital_status              True
age                         True
payment_delay_month3        True
payment_delay_month2        True
payment_delay_month1        True
bill_amount_month3          True
bill_amount_month2          True
bill_amount_month1          True
previous_payment_month3     True
previous_payment_month2     True
previous_payment_month1     True
previous_payment_month4     True
dtype: bool

In [3]:
#移除部分有缺失項目
data= data.fillna(method='ffill')

In [4]:
#檢查是否已經沒有缺失項目
data.isnull().any()

id                         False
credit_limit               False
gender                     False
education_level            False
marital_status             False
age                        False
payment_delay_month3       False
payment_delay_month2       False
payment_delay_month1       False
bill_amount_month3         False
bill_amount_month2         False
bill_amount_month1         False
previous_payment_month3    False
previous_payment_month2    False
previous_payment_month1    False
previous_payment_month4    False
dtype: bool

In [5]:
#change all the data in train123mo.csv from str to float
data['id'] = data['id'].astype(float)
data['credit_limit'] = data['credit_limit'].astype(float)
data['gender'] = data['gender'].astype(float)
data['education_level'] = data['education_level'].astype(float)
data['marital_status'] = data['marital_status'].astype(float)
data['age'] = data['age'].astype(float)

data['payment_delay_month3'] = data['payment_delay_month3'].astype(float)
data['payment_delay_month2'] = data['payment_delay_month2'].astype(float)
data['payment_delay_month1'] = data['payment_delay_month1'].astype(float)

data['bill_amount_month3'] = data['bill_amount_month3'].astype(float)
data['bill_amount_month2'] = data['bill_amount_month2'].astype(float)
data['bill_amount_month1'] = data['bill_amount_month1'].astype(float)

data['previous_payment_month4'] = data['previous_payment_month4'].astype(float)
data['previous_payment_month3'] = data['previous_payment_month3'].astype(float)
data['previous_payment_month2'] = data['previous_payment_month2'].astype(float)
data['previous_payment_month1'] = data['previous_payment_month1'].astype(float)
'''
X = data[['id','credit_limit','gender','education_level','marital_status','age','payment_delay_month3',
          'payment_delay_month2','payment_delay_month1','bill_amount_month3','bill_amount_month2',
        'bill_amount_month1','previous_payment_month3','previous_payment_month2','previous_payment_month1']].values
'''
# use 'credit_limit','education_level','marital_status','age','payment_delay_month3','payment_delay_month2',
# 'bill_amount_month3','bill_amount_month2','bill_amount_month1','previous_payment_month3','previous_payment_month2','previous_payment_month1'
# as parameter (only bill of 3 months) to cross validation previous_payment_month4

X = data[['credit_limit','education_level','marital_status','age','payment_delay_month3',
          'payment_delay_month2','bill_amount_month3','bill_amount_month2',
          'bill_amount_month1','previous_payment_month3','previous_payment_month2','previous_payment_month1']].values

Y = data[['previous_payment_month4']].values

In [6]:
#- Normal Equation
def normal_equation(data_x, data_y):
    #- Calculate the number of rows of data_x, labeled as m
    m = len(data_x)
    #- Add a spacer column to x
    #x = np.c_[np.ones((m,1)), data_x]
    
    #- Theta = (xTx)^(-1)xTy 
    xTx = data_x.transpose().dot(data_x)
    theta = np.linalg.inv(xTx).dot(data_x.transpose()).dot(data_y)
    return theta


#- preprocess data
x = np.array(X)
y = np.array(data['previous_payment_month4'])[:, np.newaxis]

In [7]:
#Find theta using Normal Equation because parameter less than 1000
# each wight as parameter as follow 
theta_ne = normal_equation(x, y)
print('theta_ne ', theta_ne)
max(theta_ne)

theta_ne  [[ 1.43670461e-03]
 [ 7.27186632e+01]
 [ 6.19918221e+01]
 [ 1.94036521e+00]
 [-8.30657526e+02]
 [ 6.90778099e+02]
 [ 1.21613599e-01]
 [-6.48386131e-02]
 [-3.76420953e-02]
 [ 3.03754943e-01]
 [ 1.23342377e-01]
 [ 1.09797122e-01]]

array([690.77809894])

In [8]:
#  Find theta using Scikit-learn
# each wight as parameter as follow 
reg = LinearRegression().fit(x, y)
theta_scikit = np.c_[reg.intercept_, reg.coef_]
print('theta_scikit ', theta_scikit.transpose())
max(theta_ne)

theta_scikit  [[ 2.25773864e+02]
 [ 1.25277822e-03]
 [ 3.22940095e+01]
 [ 5.60150231e+01]
 [-1.72069835e+00]
 [-8.42442117e+02]
 [ 6.82096146e+02]
 [ 1.21600930e-01]
 [-6.48187547e-02]
 [-3.75494436e-02]
 [ 3.03661690e-01]
 [ 1.23472276e-01]
 [ 1.09706670e-01]]

array([690.77809894])

In [9]:
# change the data type of gender,education_level,marital_status as new data train123mo.csv
# classify gender 1 as men and 0 as female
# classift education_level 0 as high school,1 as university and univiersity,2 as graduate school,3 as others,4 as unknow
# stimulate the label_month5_payment in train.csv

path1 = 'C:\\Users\\user\\titan\\train0.csv'
data1 = pd.read_csv(path1, header=None,names=['id','credit_limit','gender','education_level','marital_status','age','payment_delay_month4',
                                            'payment_delay_month3','payment_delay_month2','bill_amount_month4','bill_amount_month3','bill_amount_month2',
                                             'previous_payment_month4','previous_payment_month3','previous_payment_month2','label_month5_payment'])

data1

,id,credit_limit,gender,education_level,marital_status,age,payment_delay_month4,payment_delay_month3,payment_delay_month2,bill_amount_month4,bill_amount_month3,bill_amount_month2,previous_payment_month4,previous_payment_month3,previous_payment_month2,label_month5_payment
0,0,75659.32872,1.0,2.0,1.0,53.0,-1.0,0.0,0.0,43.673872,97.336043,617.642189,97.336043,617.642189,515.513381,0
1,1,10119.28851,0.0,0.0,1.0,46.0,0.0,0.0,NaN,2.378414,217.039935,107.684919,209.732445,0.000000,100.594674,0
2,2,13374.80610,0.0,1.0,1.0,31.0,1.0,1.0,1.0,14301.916330,13506.342420,5892.633733,397.170110,752.120619,397.170110,0
3,3,157744.09660,1.0,2.0,1.0,34.0,0.0,0.0,0.0,8154.002723,14278.876050,18234.124720,14368.707270,18400.055470,1547.887184,0
4,5,120385.03030,0.0,2.0,0.0,29.0,1.0,1.0,1.0,10575.092340,7130.249304,1572.472869,193.835523,397.170110,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20643,23203,48443.44654,1.0,2.0,0.0,29.0,-1.0,-1.0,-1.0,64.409146,64.409146,64.409146,64.409146,64.409146,414.621668,0
20644,23204,110098.06710,0.0,1.0,1.0,36.0,1.0,1.0,1.0,21815.729230,19717.923360,15197.977010,783.841260,754.001390,240.003713,0
20645,23205,237841.42300,0.0,1.0,1.0,42.0,1.0,1.0,1.0,197659.246100,202892.399200,147770.694800,3632.499761,2915.937494,397.170110,0
20646,23206,105024.75430,0.0,1.0,1.0,34.0,-1.0,-1.0,-1.0,0.000000,0.000000,0.000000,0.000000,0.000000,10.739167,0
20647,23207,141487.28530,0.0,1.0,1.0,28.0,1.0,1.0,1.0,87698.812010,90076.120680,91633.455600,1788.854382,1461.488930,3527.432995,0

In [10]:
#檢查是否有缺失項目
data1.isnull().any()

id                         False
credit_limit               False
gender                      True
education_level             True
marital_status              True
age                         True
payment_delay_month4        True
payment_delay_month3        True
payment_delay_month2        True
bill_amount_month4          True
bill_amount_month3          True
bill_amount_month2          True
previous_payment_month4     True
previous_payment_month3     True
previous_payment_month2     True
label_month5_payment       False
dtype: bool

In [11]:
#移除部分有缺失項目
data1= data1.fillna(method='ffill')

In [12]:
#檢查是否有缺失項目已沒缺失項
data1.isnull().any()

id                         False
credit_limit               False
gender                     False
education_level            False
marital_status             False
age                        False
payment_delay_month4       False
payment_delay_month3       False
payment_delay_month2       False
bill_amount_month4         False
bill_amount_month3         False
bill_amount_month2         False
previous_payment_month4    False
previous_payment_month3    False
previous_payment_month2    False
label_month5_payment       False
dtype: bool

In [13]:
#change all the data in train123mo.csv from str to float
data1['id'] = data1['id'].astype(float)
data1['credit_limit'] = data1['credit_limit'].astype(float)
data1['gender'] = data1['gender'].astype(float)
data1['education_level'] = data1['education_level'].astype(float)
data1['marital_status'] = data1['marital_status'].astype(float)
data1['age'] = data1['age'].astype(float)

data1['payment_delay_month4'] = data1['payment_delay_month4'].astype(float)
data1['payment_delay_month3'] = data1['payment_delay_month3'].astype(float)


data1['bill_amount_month4'] = data1['bill_amount_month4'].astype(float)
data1['bill_amount_month3'] = data1['bill_amount_month3'].astype(float)
data1['bill_amount_month2'] = data1['bill_amount_month2'].astype(float)

data1['previous_payment_month4'] = data1['previous_payment_month4'].astype(float)
data1['previous_payment_month3'] = data1['previous_payment_month3'].astype(float)
data1['previous_payment_month2'] = data1['previous_payment_month2'].astype(float)

X1 = data1[['credit_limit','education_level','marital_status','age','payment_delay_month4',
          'payment_delay_month3','bill_amount_month4','bill_amount_month3','bill_amount_month2',
          'previous_payment_month4','previous_payment_month3','previous_payment_month2']].values

In [14]:
x1 = np.array(X1)
y1 = np.array(data1['previous_payment_month4'])[:, np.newaxis]
theta_ne1 = normal_equation(x1, y1)

p5=theta_ne1.T.dot(x1.T)


previous_payment_month5=p5.tolist()

In [15]:
previous_payment_month5

[[97.33604262795721,
  209.73244539861528,
  397.17011039794124,
  14368.707269998222,
  193.8355228010625,
  438.62664990080503,
  -1.174772930638555e-10,
  239.25580499506373,
  86.22641310058746,
  10119.28851000101,
  -2.2394449838104626e-09,
  166.98946099861234,
  396.508270501252,
  724.769158298625,
  220.27098539930145,
  265.39922300104615,
  1353.435217000866,
  637.2262686986783,
  -9.68402344103496e-10,
  397.1701104008488,
  476.7598064021634,
  7.577373702321069e-10,
  54.452054041083215,
  209.73244540122852,
  870.0659197008582,
  100.59467439961243,
  209.7324454006233,
  1026.2004720012796,
  239.25580499785687,
  13.454342639341213,
  -2.1254457154939815e-09,
  1145.3745770009034,
  7.556891937373165e-10,
  755.6948868982271,
  752.1206185984579,
  1627.5778390008772,
  1.3085101822957077,
  447.4220816013639,
  94.96841802787272,
  153.19162880037752,
  1788.8543820004497,
  15.415445071921372,
  569.0494111978722,
  481.57068799817955,
  7645.420762998005,
  604.8345649009555,
  335.63392240212,
  1354.7041819990736,
  261.89250159871824,
  166.98946100091916,
  397.17011040057645,
  2627.2332060012964,
  1262.0778789976944,
  2.2601230703018206e-10,
  413.78725169804176,
  1070.204813000974,
  2274.6179970013764,
  967.3208879988384,
  239.25580500082776,
  6.346130872167579e-10,
  497.4453769988762,
  -1.5911224722635605e-10,
  965.3439397982954,
  6.772187684521945e-10,
  332.11743420076823,
  316.22776600134677,
  140.04109849861243,
  2.897706840739884e-09,
  944.6350422012932,
  397.1701104021958,
  324.15312640051576,
  247.65886430139747,
  2015.1892860017886,
  1499.3818189986625,
  2206.5518339984037,
  4.970222888678172e-10,
  239.25580499832952,
  481.570688002297,
  6.245098648057639e-10,
  1136.9949469988062,
  554.151283000835,
  569.0494112010472,
  954.6824309989224,
  826.9203252983459,
  109.47241810227544,
  482.2587442983707,
  752.1206185981109,
  2.0430636051864763e-09,
  -2.678761768791056e-09,
  140.98214329879113,
  762.4764580007856,
  1752.703733998724,
  779.8618928011404,
  195.27027630090333,
  254.30160869811212,
  1677.7586860016,
  445.8972994088051,
  177.91343209769036,
  12709.44352999919,
  774.7515260979093,
  399.9853885988661,
  752.1206186011178,
  828.0702630984327,
  289.1148960012558,
  166.98946099869806,
  752.1206185988276,
  481.5706880014091,
  493.29424210221174,
  397.1701104014659,
  472.472562799212,
  239.25580500003574,
  1785.0538749983903,
  1222.5806559981827,
  413.78725170166376,
  583.4897518016267,
  3.227696440588771e-09,
  3.9553001578930344e-10,
  361.75248890093604,
  -4.5802828357848643e-10,
  1.0036409520037302e-09,
  1353.4352169982556,
  8.079594044388566,
  4.730547585242843e-10,
  1.1988070831018377e-09,
  1150.4901370010614,
  771.9153411012993,
  481.5706880008952,
  269.52765960113055,
  1824.702739998913,
  397.170110398182,
  1.4934790292884815e-09,
  -1.8493410957085097e-09,
  533.7089490008656,
  -9.98499266405721e-10,
  -9.376113321595791e-10,
  139.63817990132264,
  447.4220815987765,
  123.97863050068777,
  248.11065910065838,
  68.45956937877989,
  32.100031229707504,
  944.6350421980925,
  309.1287229011143,
  6.367888439835976e-10,
  239.25580499966344,
  100.5946743986868,
  91.87104890839154,
  268.76217369821813,
  292.224316300995,
  126.34310520049563,
  163.2406902981479,
  1788.8543820009877,
  7.228402691457186e-10,
  277.97655730140906,
  0.01788854202655067,
  1788.8543820014008,
  752.1206185984435,
  569.0494111986777,
  1.2376213454092648e-09,
  100.59467440083058,
  2.648985074238299e-09,
  495.1959819982656,
  76.10925536086029,
  166.989461000725,
  10532.041310003513,
  195.7011146009592,
  100.59467440048022,
  481.5706879980872,
  100.84622389845637,
  -1.2109430160721097e-09,
  -1.78805747318311e-09,
  579.7390188018919,
  752.120618601342,
  1788.854382001704,
  1788.8543820015448,
  2088.733454001294,
  -1.5339820593706442e-09,
  1145.3745770010407,
  48.40541893023463,
  397.17011039837683,
  414.28786140153653,
  113.8377572014096,
  641.0484210005565,
  184.56174840199185,
  391.7165511010464,
  4.3190996644754804e-10,
  771.159376599283,
  156.61868369562453,
  2.8091783661823687e-09,
  239.25580500075634,
  752.1206186010822,
  403.80060809866666,
  2223.587930999344,
  -2.0805202107037848e-09,
  269.5276595986538,
  1.881732146380346e-09,
  1353.4352170017553,
  1193.0207870012712,
  2855.9010739977616,
  22.2414949388636,
  145.70613710074866,
  1145.3745769983634,
  31.003144749933274,
  2.4983024171844984e-09,
  269.5276596007564,
  239.255805001439,
  254.30160869889804,
  3.5340331492003598e-09,
  735.2361534984706,
  403.3025603012886,
  2.2853717235117326e-09,
  244.35074919822586,
  13327.00826999826,
  659.3114703009983,
  239.2558050009294,
  3004.968281000203,
  298.4630089010525,
  229.13102179787214,
  1354.4926710010952,
  752.1206186011634,
  262.3493705007422,
  125.42252620096184,
  -6.208809660039269e-11,
  464.4336040005575,
  4278.84871100114,
  80.4142167112432,
  240.60237509803682,
  2.4924970639904352e-11,
  1395.6486409979582,
  443.1891500009076,
  1579.231125999663,
  914.4258673981379,
  569.0494111980657,
  305.1988065980275,
  126.21151160174772,
  397.1701103990757,
  55.454844187932586,
  313.2264615979017,
  397.1701103983249,
  254.30160870094457,
  397.17011039905094,
  2377.6018110014306,
  166.98946100084927,
  430.5389646007443,
  -8.660339605264848e-10,
  415.7904159975135,
  3.956259853520147e-10,
  1.7698146444614763e-09,
  944.6350421986616,
  31.900031271051013,
  73.73832064058617,
  2724.6616610010774,
  -7.133346821159128e-10,
  18836.956459998186,
  1145.3745770010826,
  185.1298054021242,
  196.13214259865236,
  -1.2132691413558708e-09,
  1145.3745769979578,
  239.2558049979747,
  1.122425969576969e-09,
  965.739264698474,
  239.70449369866225,
  1788.8543819990996,
  -3.143315111775371e-10,
  948.178751001771,
  481.5706880006244,
  1145.3745770012365,
  131.23120410072488,
  464.4336039978601,
  4255.168553999154,
  7956.414752998297,
  1.4957068714866312e-09,
  346.066509197318,
  -2.102756762733737e-09,
  143.67775730922168,
  102.48434790137377,
  161.85659390074446,
  73.73832063790917,
  2.871817327984045e-09,
  752.1206185980371,
  2.9179882027625215e-11,
  1856.411384998604,
  2.410911471705148e-09,
  944.6350422006275,
  -2.302930211259235e-11,
  166.9894609989479,
  237.014888600756,
  255.51314489693252,
  170.05652669913346,
  31.00314474774764,
  4254.902633998877,
  241.05156730076783,
  614.2095418015954,
  569.0494112010597,
  229.87249790083953,
  504.032186400684,
  285.39240520096064,
  0.27885479879843716,
  -2.019632141111052e-09,
  239.2558049986473,
  106.92065559933933,
  366.79464629851634,
  1568.1157829982606,
  397.1701104011541,
  1171.8195989982246,
  160.75101760122487,
  -2.8882257925553087e-09,
  239.2558049986124,
  9843.035512001692,
  4308.952324999158,
  100.59467440079301,
  2.2126131287112557e-10,
  1.6904851286459525e-11,
  9.888352788255637e-10,
  4649.870889998931,
  187.26312029815386,
  2363.88116099874,
  239.25580500156804,
  752.1206186004592,
  0.20367960414899275,
  867.3565198985568,
  112060.87949999931,
  209.73244540079762,
  144.7588521990773,
  239.2558049986735,
  9.302876764489813e-10,
  1148.2387289983417,
  162.40994959756472,
  752.1206185979869,
  187.97530960072032,
  5.4455237548808,
  239.2558050012981,
  100.59467440098825,
  7.521542897636281e-10,
  209.7324454015778,
  24.779753921047238,
  -2.2482222986514096e-09,
  1587.3050100013133,
  4.774522030960917e-10,
  1804.296535998452,
  171.03474559843798,
  239.25580499831779,
  313.2264616009664,
  569.0494111989498,
  1788.8543819983017,
  1354.7041819983901,
  113.32242140088715,
  239.2558050006989,
  398.32886089744386,
  1684.8259050007807,
  2285.884981001234,
  120.31845600090351,
  2.575582191621679e-09,
  1.4024450702647673e-09,
  6479.217043001514,
  -2.1133919983445023e-09,
  125.55395499834208,
  1827.1725289980407,
  397.17011040180375,
  73.73832063855522,
  297.2131644971967,
  239.2558049977931,
  945.6191395006513,
  101.60162509828291,
  318.12626969851385,
  366.30608619790024,
  -5.233109484688994e-12,
  1883.483127001093,
  1047.0514299986748,
  397.17011040077233,
  -2.2303423783659872e-09,
  2.332996901475475e-10,
  239.25580499806887,
  17197.097130001148,
  569.0494112012162,
  153.46523409909113,
  239.25580500060158,
  847.2827234976252,
  397.1701104018679,
  -2.2859294281143e-09,
  209.73244540056035,
  1788.854381998724,
  239.25580500132295,
  886.9406301980299,
  -2.913404503926842e-09,
  9.196711604115065e-09,
  754.7539614995395,
  -2.0890900602280567e-09,
  24.68477599176907,
  4272.1943280010355,
  3823.3618499990716,
  171.45432540091326,
  -1.0727591174637872e-09,
  42.824195378176945,
  866.58271629916,
  264.7886888989437,
  697.8078523981613,
  17501.069969999924,
  2969.53920199815,
  1279.4102869982257,
  1083.133839001915,
  300.4962394006733,
  305.19880660177535,
  789.9128316010625,
  18034.7669400005,
  24.874804721744894,
  754.377657001147,
  140.04109849929324,
  2735.124934000846,
  -2.4999612637376813e-09,
  -5.504270060135669e-10,
  293.9373267010069,
  397.1701104012077,
  -1.1217449198328641e-09,
  9.390507480677096,
  1541.373059998665,
  1019.6018919991812,
  569.0494111971482,
  1.8055154949649117e-09,
  3.0284728401257553e-09,
  2814.465629003258,
  921.6659636022711,
  828.4536467011454,
  2971.519026999075,
  682.2831730012948,
  239.25580499873996,
  6.222430213879831e-10,
  279.9811556981199,
  -1.2383492069257228e-09,
  789.9128315958006,
  2379.495560001697,
  2969.5392020013724,
  100.59467439854168,
  239.2558049976688,
  523.5458460017643,
  770.9704085983508,
  397.1701103989044,
  124.37208849844795,
  2.221508650442245e-09,
  26.30919875166377,
  239.2558050010559,
  166.98946100077086,
  2015.189285999216,
  2527.1672340014093,
  7.886202960186335e-10,
  100.59467439797427,
  262.19706319815714,
  397.1701103985273,
  3417.1337860018366,
  427.6818178984001,
  3331.8339920011904,
  947.587948601663,
  239.25580499784076,
  181.01933600075407,
  -1.1985293466455665e-09,
  752.1206186010303,
  209.73244540123093,
  -1.5554518658354753e-09,
  129.11288010152026,
  477.61818349934316,
  1145.3745770009848,
  166.98946100065348,
  569.0494112007092,
  4962.936708000787,
  500.2166579007222,
  236.56721209859532,
  455.57176589860313,
  378.3950073974697,
  122.9306308013494,
  2.6034428375897554e-09,
  4225.671777998339,
  223.36404030100084,
  602.1356170981405,
  498.1379085000455,
  944.6350422007979,
  1068.9943109987364,
  260.674963998364,
  31.800125158211838,
  1895.2384929991765,
  56.12539560888778,
  397.17011039889314,
  166.98946100239192,
  397.17011040225736,
  43.46114004812719,
  137.09177559815785,
  139.63817990164281,
  263.8734154984265,
  159.7848839014571,
  2175.348541998338,
  1428.065389999023,
  166.98946099787338,
  1788.8543820008495,
  13531.473990001652,
  239.2558050019712,
  413.7872516983667,
  413.7872516982633,
  270.90663009889875,
  6057.131659001538,
  2276.025760997983,
  288.9595998011317,
  569.0494112020064,
  332.11743420080296,
  169.358487001358,
  82.46340780839434,
  1.6386561116775637e-10,
  1145.3745770005164,
  -2.4583087310886705e-10,
  271.826724797754,
  126.34310519824848,
  569.0494112010956,
  200.74151820143825,
  265.85730800089874,
  51.13623157206948,
  569.0494111989424,
  944.6350422013287,
  397.1701103982214,
  436.9392357002064,
  1044.038910998211,
  397.17011040088966,
  5623.975599002202,
  195.27027629850957,
  166.9894610016979,
  784.9789658986407,
  332.1174341993479,
  1145.374576998145,
  757.389143198963,
  245.8533348012062,
  1353.435216998037,
  169.21894800092747,
  852.0995620979244,
  93.35522234835058,
  139.63817989853646,
  -2.3808085067079766e-09,
  153.19162879914916,
  -1.4705510169529671e-09,
  397.17011040062346,
  912.4710473011335,
  1145.3745769974169,
  3949.2311080010804,
  26793.76824999901,
  397.17011040104313,
  239.25580500047943,
  944.635042198329,
  944.6350421980378,
  0.20367960360534648,
  502.817525798368,
  752.120618598408,
  133.62251650147476,
  100.59467439875503,
  254.30160869761977,
  366.7946463030544,
  946.0128358005879,
  677.6762706987998,
  944.6350421985634,
  245.10181169772918,
  239.25580500068327,
  209.73244540198135,
  332.1174341985096,
  239.255805001322,
  483.11909099811083,
  166.98946100200843,
  202.4755326007863,
  -2.117372617037746e-09,
  397.1701103983225,
  239.25580499951698,
  139.36969660093064,
  7657.681137997941,
  1.5618655133806447e-09,
  606.2749899014387,
  191.8304330010309,
  753.8132706009401,
  595.1296823011631,
  1151.1043099972671,
  1419.0932620014012,
  240.00371289509522,
  938.9313243989889,
  101.47564660082875,
  -2.6262009125865743e-09,
  0.10119288182764193,
  220.41807790110673,
  127.0014846009293,
  127.0014845983408,
  665.9111649019812,
  284.927773397631,
  53.0100870180338,
  -2.263923467844708e-09,
  161.02726950078002,
  4692.677791998287,
  1988.660536000866,
  251.42883869779106,
  222.4794306012626,
  13.454342640796604,
  5623.413251998825,
  126.3431052008515,
  105.77630719819207,
  261.892501600659,
  208.71340870127025,
  1788.8543819985537,
  533.7089490013378,
  569.0494112009387,
  101.8536756998989,
  -2.0198991980838863e-09,
  195.27027630078422,
  3.513423438206301e-09,
  656.7484791007229,
  1044.038910999699,
  139.772460300632,
  399.6539731007681,
  37637.17430000138,
  137.22556280133117,
  231.80257360061614,
  944.63504219802,
  554.6819945015235,
  316.22776600075724,
  1459.9858489987166,
  316.2277660001106,
  4374.365651998117,
  73.7383206417808,
  1296.1607939981936,
  305.0418195015564,
  200.59715169793384,
  1023.6000160008493,
  251.73092789833666,
  1383.955721001301,
  481.7426836010354,
  32520.18798000104,
  239.25580499880286,
  100.59467439824873,
  47.21345608859884,
  964.3557690980905,
  214.40347789980663,
  -1.874595296769704e-09,
  209.73244540028838,
  269.5276596008277,
  14892.616260003319,
  1206.8524979988022,
  2051.4358249953298,
  1572.6907869985646,
  481.5706879983651,
  13374.806100000991,
  8.875816882998339e-10,
  224.3969710008858,
  34.31629940879194,
  239.25580500022133,
  720.4789323008702,
  183.71031849823927,
  446.574851798857,
  -1.9032268845005495e-09,
  239.2558049978409,
  135.48836960111805,
  752.1206185979325,
  139.6381799007249,
  2.132887045239623e-09,
  31.600501261035127,
  312.27987240223405,
  239.2558050016493,
  166.98946099905473,
  11.71227546056704,
  240.752087200938,
  356.23850249858003,
  37.488218728146734,
  166.98946100154376,
  547.4377539002562,
  230.16922239836023,
  786.8758746986309,
  179.60622899870754,
  100.59467439648864,
  695.4006615033124,
  647.7937821014813,
  126.3431051976922,
  10.578641980500718,
  31.003144748568996,
  944.6350422013024,
  752.12061860103,
  195.27027630052038,
  239.2558049985866,
  397.1701104015116,
  4469.227377999011,
  163.79498789812217,
  156.3439622980661,
  758.1423895011682,
  9483.96847799889,
  316.227765998323,
  752.1206185983922,
  -1.6765432025208011e-09,
  146.383524600826,
  821.1754377011182,
  9.85474174046595e-10,
  -1.0814974994820938e-09,
  239.2558049985649,
  244.50092480134612,
  713.2158743008758,
  155.3831980975286,
  89.28527552905574,
  -2.119025905276703e-09,
  9.676480869804173e-10,
  111.0092236022159,
  1353.4352169986357,
  598.3611527985016,
  225.57862859994748,
  150.5972659000773,
  284.9277734007303,
  30.012659771345273,
  318.9179829008412,
  5029.389299998771,
  250.67393330147934,
  1513.857704001274,
  944.6350422004143,
  8102.851285998011,
  734.6746616979456,
  9.390507481444178,
  31.003144748297203,
  239.25580500107327,
  3093.781313000839,
  534.762529798409,
  634.8624684011642,
  332.117434200935,
  828.0702630982871,
  24.779753915212222,
  3960.7617070015694,
  142.05916320061746,
  1.0067177233953963e-09,
  239.25580500068315,
  239.25580500148635,
  158.13137200177692,
  877.2345957000925,
  29.618277330703155,
  263.2635855981797,
  1901.3480030015805,
  488.1151359017857,
  2.621806205068706e-09,
  8.003729514074815,
  113.19366049869107,
  119.40685550121074,
  166.9894610006198,
  -8.293468228756231e-10,
  219.82982589849422,
  3.3006445036423514e-09,
  397.1701103980278,
  -1.179738974787896e-09,
  -1.0003626296438938e-10,
  1594.294459999029,
  14640.576380001175,
  1.0992571967485808e-09,
  343.3318280005086,
  166.9894610020677,
  3.6829751612789742e-09,
  7.932862474589918e-10,
  4254.636718001013,
  1949.6823959984365,
  177.06823829866983,
  563.1871534006171,
  254.30160870104962,
  -2.0586865856075547e-09,
  398.99130689806515,
  397.1701104013206,
  8225.8439900013,
  5066.811926998715,
  1157.6595679981006,
  752.1206186012137,
  3.7735701084833094e-10,
  1788.8543820006855,
  595.8474842982696,
  397.17011040066336,
  239.2558049980195,
  269.8339757988311,
  331.9577701007532,
  659.3114703014272,
  1.01345414475585e-09,
  239.25580500110482,
  187.69036900250518,
  1137.1991819984246,
  752.1206186007201,
  397.1701103980173,
  2130.331992999941,
  -1.8693503168677414e-09,
  2.149041551230517e-10,
  0.042546364951756614,
  105.90333529848039,
  255.2101529004803,
  239.25580500130923,
  4743.170962997945,
  -1.6489086850156077e-09,
  1.1358529292173833e-09,
  145.9770166982839,
  413.7872516980122,
  101.60162510096151,
  2.6130330303794444e-09,
  754.377656998899,
  1568.1157830008417,
  139.63817990127734,
  100.59467440094066,
  831.3301542984992,
  1353.4352169985978,
  165.3212396955261,
  1145.374577000945,
  115.90375799737163,
  254.15024770060938,
  24.77975391831354,
  179.88867310103868,
  238.80728450129234,
  251.57987419772934,
  239.2558050013702,
  518.1299321982888,
  1248.5374349985912,
  133.8887498009748,
  1860.0164170010125,
  817.3499699983595,
  39.772572308332926,
  944.6350422007582,
  146.79025839899757,
  2110.8989279992743,
  219.97685939875532,
  752.4966977007701,
  931.2717246982594,
  76.10925535998193,
  43.142432620286726,
  316.2277660011644,
  991.9018977993894,
  752.1206185981174,
  239.25580499775725,
  348.16065790255595,
  752.12061859828,
  397.17011040128335,
  239.25580499994896,
  239.25580499992878,
  139.63817989683093,
  10739.96549999833,
  1946.7254710010473,
  944.6350422012351,
  373.4846378011857,
  1354.7041820013033,
  104.63442950097475,
  239.255805000084,
  6330.884885998639,
  552.0294538985568,
  132.69153580224827,
  98782.48959999885,
  4.371342843583255e-10,
  45.16876936135232,
  269.5276596004988,
  1165.8640880008977,
  6.662214557277013e-10,
  267.0796396987256,
  239.25580499907275,
  126643.72259999873,
  126.34310519904186,
  569.0494111983852,
  100.5946743985227,
  239.25580499769586,
  100.59467439886619,
  120.0578572979073,
  1410.7721450011932,
  752.1206185986943,
  1788.854382001375,
  1661.2182280013403,
  398.9913068975237,
  398.16328369819786,
  -1.2605274454155518e-09,
  2742.6731940009577,
  440.8222305018289,
  1345.8264309985361,
  1788.8543820008927,
  2016.7924050021713,
  239.25580499851634,
  18.946093441426548,
  4708.682734998926,
  56.237310640387335,
  1562.0199279986002,
  433.9051740007192,
  876.2651687008989,
  569.0494112008424,
  6.596487509897691e-10,
  316.22776600103555,
  250.22120819816234,
  239.25580500128365,
  5.512334174529247e-10,
  424.66075950093494,
  100.21758589771824,
  284.92777340121114,
  165.32123970076947,
  15124.262220001101,
  1.5707787475040952e-09,
  25.16039263036036,
  211.77348940075635,
  455.40168120144307,
  752.1206186008422,
  -3.4108407460871412e-09,
  17184.44010999792,
  -1.99724573957838e-09,
  2.0181777887861654e-09,
  1.3914746845881443e-10,
  397.1701104007617,
  307.39832100124676,
  181.30222290093508,
  209.73244539782232,
  239.25580500198535,
  -1.053855716454284e-09,
  198.72228219925174,
  42.294850540216686,
  289.4255384001845,
  265.0939207980849,
  480.7108939015147,
  290.6687744978646,
  1802.9526870012032,